name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install npm dependencies
      run: npm install
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-18-230-24-185.sa-east-1.compute.amazonaws.com"
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home/ec2-user/teste"