const { Model, DataTypes } = require("sequelize");

class Clientes extends Model {
    static init(sequelize) {
        super.init({
            CODCLI: {
                type: DataTypes.INTEGER(10),
                primaryKey: true,
                allowNull: false,
                autoIncrement: false,
            },
            CLASSE: DataTypes.INTEGER(3),
            RAZCLI: DataTypes.STRING,
            FANT: DataTypes.STRING(80),
            CGCCLI: DataTypes.STRING(80),
            INSCLI: DataTypes.STRING(30),
            ENDCLI: DataTypes.STRING(150),
            BAIRROCLI: DataTypes.STRING(60),
            MUNCLI: DataTypes.STRING(60),
            ESTCLI: DataTypes.STRING(10),
            CEPCLI: DataTypes.STRING(20),
            TELCLI: DataTypes.STRING(50),
            TEL2CLI: DataTypes.STRING(50),
            TEL2CLI: DataTypes.STRING(50),
            FAXCLI: DataTypes.STRING(50),
            REPRCLI: DataTypes.INTEGER(10),
            REPRCLI2: DataTypes.INTEGER(10),
            DATACLI: DataTypes.DATE,
            CONTATOCLI: DataTypes.STRING(50),
            ENDCOBCLI: DataTypes.STRING(150),
            BAIRROCOBCLI: DataTypes.STRING(60),
            MUNCOBCLI: DataTypes.STRING(60),
            ESTCOBCLI: DataTypes.STRING(2),
            CEPCOBCLI: DataTypes.STRING(20),
            FONECOBCLI: DataTypes.STRING(20),
            FAXCOBCLI: DataTypes.STRING(20),
            CONTATOCOBCLI: DataTypes.STRING(50),
            ENDENTCLI: DataTypes.STRING(150),
            BAIRROENTCLI: DataTypes.STRING(60),
            MUNENTCLI: DataTypes.STRING(60),
            ESTENTCLI: DataTypes.STRING(2),
            CEPENTCLI: DataTypes.STRING(20),
            FONEENTCLI: DataTypes.STRING(30),
            CONTATOENTCLI: DataTypes.STRING(50),
            FAXENTCLI: DataTypes.STRING(20),
            SQualidade: DataTypes.INTEGER(3),
            IMPORTACAO: DataTypes.STRING(1),
            ValidadeCertificado: DataTypes.DATE,
            Qualidade: DataTypes.STRING(40),
            Pontuacao: DataTypes.INTEGER,
            ClasseMP: DataTypes.STRING(30),
            Fabrica: DataTypes.STRING(20),
            Email: DataTypes.STRING,
            Revisao: DataTypes.INTEGER(10),
            DataRev: DataTypes.DATE,
            TAXAFIN: DataTypes.DOUBLE,
            CONDPAG: DataTypes.INTEGER,
            TRANSPORTE: DataTypes.INTEGER,
            Fantasia: DataTypes.STRING(40),
            Site: DataTypes.STRING(60),
            RAMO: DataTypes.STRING(50),
            UsuarioCli: DataTypes.STRING(30),
            NRO: DataTypes.STRING(10),
            NROC: DataTypes.STRING(10),
            NROE: DataTypes.STRING(10),
            LMPCLI: DataTypes.INTEGER(5),
            NLMPCLI: DataTypes.INTEGER(5),
            PF: DataTypes.INTEGER(5),
            ObsDiversas: DataTypes.TEXT,
            ADTOVALOR: DataTypes.DOUBLE,
            PERCURSO: DataTypes.INTEGER(10),
            TEMPO: DataTypes.STRING(5),
            PEDAGIO: DataTypes.DOUBLE(15, 5),
            CUSTO: DataTypes.DOUBLE(15, 5),
            FONTE: DataTypes.STRING(2),
            FRETE: DataTypes.INTEGER(5),
            NFE: DataTypes.STRING(200),
            CODMUN: DataTypes.INTEGER(10),
            CODMUNC: DataTypes.INTEGER(10),
            CODMUNE: DataTypes.INTEGER(10),
            CODPAIS: DataTypes.INTEGER(10),
            CODPAISC: DataTypes.INTEGER(10),
            CODPAISE: DataTypes.INTEGER(10),
            PAIS: DataTypes.STRING(100),
            PAISC: DataTypes.STRING(100),
            PAISE: DataTypes.STRING(100),
            DTNFE: DataTypes.DATE,
            TCOM: DataTypes.INTEGER(10),
            TREC: DataTypes.INTEGER(10),
            RG: DataTypes.STRING(15),
            OBSFIN: DataTypes.TEXT,
            UltimaAlteracao: DataTypes.DATE,
            UsuarioAlteracao: DataTypes.STRING(50),
            SituacaoCli: DataTypes.STRING(45),
            senhaRoot: DataTypes.STRING,
            Complemento: DataTypes.STRING,
            ComplementoCob: DataTypes.STRING,
            ComplementoEnt: DataTypes.STRING,
            Banco: DataTypes.STRING,
            Agencia: DataTypes.STRING,
            ContaCorrente: DataTypes.STRING,
            DREBOR: DataTypes.INTEGER(4),
            comissao: DataTypes.DOUBLE(15, 5),
            TipoCliente: DataTypes.STRING(45),
            Limite: DataTypes.DOUBLE(15, 5),
            ObsFat: DataTypes.STRING(200),
            DescontoICMS: DataTypes.DOUBLE(15, 5),
            DescontoPisCofins: DataTypes.DOUBLE(15, 5),
            situacaoCadastro: {
                type: DataTypes.STRING,
                allowNull: true,
                primaryKey: false,
                autoIncrement: false,
            },
            provedor: DataTypes.INTEGER(1),
            LOJA: DataTypes.STRING(2),
            ObsFinanceira: DataTypes.STRING(2000),
            HOMOLOGADO: DataTypes.STRING(3),
        }, {
            sequelize,
            tableName: "clientes",
        })
    }
}